### PR TITLE
Aquaplanet extra sst cases

### PR DESCRIPTION
**Pull request by gitleviglenn**
this merge simply adds a few test cases to the ice_model.F90 file in the src/coupler/simple directory.  the test cases are fundamentally no different than other standard test cases that have been present for years.

### CODE REVIEW

**Review by thomas-robinson — CHANGES_REQUESTED** [review]
@gitleviglenn Can you add some documentation/comments about what the test cases do and how the SST is distributed?  Or if it's already in there, can you let me know which line because I don't see it anywhere.

**Comment by gitleviglenn** [comment]
The changes to the ice_model.F90 file add the additional test cases that are labelled as:
aqua_planet_20N, aqua_planet_25N, aqua_planet_30N, aqua_planet_35N, aqua_planet_40N, aqua_planet_45N, aqua_planet_50N, aqua_planet_55N, aqua_planet_60N, aqua_planet_65N, aqua_planet_70N, aqua_planet_75N, aqua_planet_80N, aqua_planet_85N, aqua_planet_90N.  For the aqua_planet_20N case a prescribed SST pattern that shifts the Control SST pattern 20 degrees to the north.  This is documented in the infile comments.   The 'Control' SST test case is also documented in the same file and users can see how it is defined.  The control case comes from Neale and Hoskins, 2000, 'A standard test for AGCMs including their physical parameterizations: I. The proposal, _Atmospheric Science Letters'_1, 101-107.  The test cases Control, aqua_planet_5N, and all cases up until aqua_planet_60N were documented and used in the recent paper, Burnett et al., 2021, 'Tropical Cyclone Frequency Under Varying SSTs in Aquaplanes Simulations. _Geophysical Research Letters'_.

**Comment by gitleviglenn** [comment]
Hi Tom,

I just replied with a comment.  The equations used are defined within the
file itself, and are plotted in Adams paper.

If you need more clarification let me know.

Levi

**Comment by thomas-robinson** [comment]
@gitleviglenn I searched the code for this comment, but couldn't find it.  Which file is this comment in?  Did I miss it?  It needs to be documented in the ice_model.F90 file.

> The changes to the ice_model.F90 file add the additional test cases that are labelled as:
> aqua_planet_20N, aqua_planet_25N, aqua_planet_30N, aqua_planet_35N, aqua_planet_40N, aqua_planet_45N, aqua_planet_50N, aqua_planet_55N, aqua_planet_60N, aqua_planet_65N, aqua_planet_70N, aqua_planet_75N, aqua_planet_80N, aqua_planet_85N, aqua_planet_90N. For the aqua_planet_20N case a prescribed SST pattern that shifts the Control SST pattern 20 degrees to the north. This is documented in the infile comments. The 'Control' SST test case is also documented in the same file and users can see how it is defined. The control case comes from Neale and Hoskins, 2000, 'A standard test for AGCMs including their physical parameterizations: I. The proposal, _Atmospheric Science Letters'_1, 101-107. The test cases Control, aqua_planet_5N, and all cases up until aqua_planet_60N were documented and used in the recent paper, Burnett et al., 2021, 'Tropical Cyclone Frequency Under Varying SSTs in Aquaplanes Simulations. _Geophysical Research Letters'_.

**Comment by gitleviglenn** [comment]
Hi Tom,

no you didn't miss it, I only put the comment on Github.  Wasn't sure what
you wanted in the file.  I will add it, or an abbreviated version, to the
ice_model.F90 file.

Levi

**Comment by thomas-robinson** [comment]
@gitleviglenn do you have a timeline for when the documentation will be added?

**Comment by gitleviglenn** [comment]
@thomas-robinson      time line: in about 10 minutes.

**Comment by gitleviglenn** [comment]
Hi @thomas-robinson, I just added a comment to document the changes.  It isn't as long as what I wrote to you.  Part of what I wrote to you was more of a description of the changes that wasn't needed within the file because some documentation was already there.  In any case, the comments should be sufficient, but let me know something else is needed.

**Review by thomas-robinson — APPROVED** [review]

**Comment by thomas-robinson** [comment]
@rem1776 this is ready now

**Review by rem1776 — APPROVED** [review]

**Pull request merged**
