### PR TITLE
implementation of CORE (Large&Yeager 2004) with multiple heights

### PR DESCRIPTION
**Pull request by raphaeldussin**
This implementation allows to use atmospheric data referenced at different heights
(e.g. ERAinterim, ERA5 for which winds are at 10m, temp and humidity at 2m)

It reproduces answers bitwise with the ncar_ocean_fluxes routine if all variables are
referenced at 10 meters.

### CODE REVIEW

**Review by nikizadehgfdl — APPROVED** [review]
This PR introduces a new functionality to enable using NCAR surface fluxes in experiments. It is isolated and have no effect on the current GFDL models. I ran OMIP4,AMIP4 and ESM4 regression tests with this PR, they all passed and preserved old answers. @thomas-robinson please consider this PR to be merged in. Thanks.

**Comment by raphaeldussin** [comment]
thanks @nikizadehgfdl

**Comment by thomas-robinson** [comment]
We will consider this for 2021.01.

**Comment by thomas-robinson** [comment]
@rem1776 is there anything else in 2021.01-alpha1? If not, you could move the tag.

**Review by wrongkindofdoctor — APPROVED** [review]

**Pull request merged**
