### PR TITLE
Add a diag_send_complete call

### PR DESCRIPTION
**Pull request by uramirez8707**
Add a diag_send_complete call. This is needed for the new diag manager. It is backwards compatible with the old diag manager.

### CODE REVIEW

**Review by rem1776 — APPROVED** [review]

**Comment by bensonr** [comment]
@rem1776 - with Niki's comment about sub-stepping in the ocean component, will this fix be sufficient?

**Comment by rem1776** [comment]
> @rem1776 - with Niki's comment about sub-stepping in the ocean component, will this fix be sufficient?

I am not sure. I was under the impression this call would be needed regardless, and other updates would go to the ocean component to handle the sub-stepping if needed.

@uramirez8707 @nikizadehgfdl What do you guys think?

**Comment by bensonr** [comment]
@rem1776 - what's the behavior for _diag_send_complete_ when I call it twice in a row with no new _send_data_ calls in between?  This is where we might end up with trouble by having it in both the component and the coupler driver.

**Comment by uramirez8707** [comment]
> @rem1776 - what's the behavior for _diag_send_complete_ when I call it twice in a row with no new _send_data_ calls in between? This is where we might end up with trouble by having it in both the component and the coupler driver.

That will not be good. 
https://github.com/NOAA-GFDL/FMS/blob/bb6de937f70a08a440f5e63b8553b047c1921509/diag_manager/fms_diag_object.F90#L688-L689

**Comment by rem1776** [comment]
> > @rem1776 - what's the behavior for _diag_send_complete_ when I call it twice in a row with no new _send_data_ calls in between? This is where we might end up with trouble by having it in both the component and the coupler driver.
> 
> That will not be good. https://github.com/NOAA-GFDL/FMS/blob/bb6de937f70a08a440f5e63b8553b047c1921509/diag_manager/fms_diag_object.F90#L688-L689

Yeah it'd be incrementing the time step along with running the reduction an extra time.

**Comment by uramirez8707** [comment]
` this%current_model_time` should be modified inside send_data instead, if there is a new time

**Comment by rem1776** [comment]
> ` this%current_model_time` should be modified inside send_data instead, if there is a new time


I could try to add that in and then have it ignore any un-needed reductions from extra calls, but would that solve the issues with the ocean model substeps?

**Comment by uramirez8707** [comment]
This is going to prevent the math from being done twice: https://github.com/NOAA-GFDL/FMS/pull/1451/commits/efbb9f0ab4dc86d3aafffac702643b2c9062a4b5

The ocean model substeps still need to call diag_send_complete. If they don't the code will crash with something like: https://github.com/NOAA-GFDL/FMS/blob/bb6de937f70a08a440f5e63b8553b047c1921509/diag_manager/fms_diag_file_object.F90#L1204-L1206

**Comment by thomas-robinson** [comment]
Is this going to add on to the model time?  I don't think the math needs to be done in fms_diag_send_complete in the ocean model because there isn't any threading.  The math should all be done in accept_data

**Pull request merged**
